version: '3.8'

services:
  dind:
    image: docker:dind
    container_name: dind
    privileged: true
    networks:
      - jenkins
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - jenkins-data:/var/jenkins_home

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: unless-stopped
    user: root
    networks:
      - jenkins
    environment:
      DOCKER_HOST: tcp://dind:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - docker-certs-client:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"

networks:
  jenkins:

volumes:
  docker-certs-ca:
  docker-certs-client:
  jenkins-data:
